using FlyRemotely.Migrations;
using FlyRemotely.Models;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Data.Entity.Migrations;

namespace FlyRemotely.DAL
{
    public class FlyRemotelyInitializer : MigrateDatabaseToLatestVersion<FlyRemotelyContext, Configuration>
    {
        public static void SeedFlyRemotelyData(FlyRemotelyContext context)
        {
            var categories = new List<Category>
            {
                new Category() { CategoryId = 1, Name = "SQL"},
                new Category() { CategoryId = 2, Name = "TypeScript" },
                new Category() { CategoryId = 3, Name = "Java" },
                new Category() { CategoryId = 4, Name = "JavaScript" },
                new Category() { CategoryId = 5, Name = "PHP" },
                new Category() { CategoryId = 6, Name = "Python" },
                new Category() { CategoryId = 7, Name = ".NET" }
            };
            categories.ForEach(x => context.Categories.AddOrUpdate(x));
            context.SaveChanges();

            var offers = new List<Offer>
            {
                new Offer() { OfferId = 1, CategoryId = 1, Status = OfferStatus.Aktywne, Title = "Administrator baz danych (MS SQL)", Type = "Pełny etat", Salary = "8 500 zł./mies.", CompanyName = "Fast Blue Engine", CompanyWebsite = "fast-b-engine.com", CompanyPhotoSource = "company1.png", Featured = true, DateAdded = DateTime.Now, Requirements = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.", Description = "Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam. Labore et dolore magna aliqua. Ut enim ad minim veniam.", CompanyDescription = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt." },
                new Offer() { OfferId = 2, CategoryId = 1, Status = OfferStatus.Aktywne, Title = "Senior SQL DWH Developer", Type = "Pełny etat", Salary = "7 500 zł./mies.", CompanyName = "FGT Tech", CompanyWebsite = "fgttecg.com", CompanyPhotoSource = "company2.png", Featured = false, DateAdded = DateTime.Now, Requirements = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.", Description = "Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam. Labore et dolore magna aliqua. Ut enim ad minim veniam.", CompanyDescription = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt." },
                new Offer() { OfferId = 3, CategoryId = 1, Status = OfferStatus.Aktywne, Title = "Młodszy programista SQL (Oracle)", Type = "1/2 etatu", Salary = "5 500 zł./mies.", CompanyName = "Yellow Code", CompanyWebsite = "yellowc.com", CompanyPhotoSource = "company3.png", Featured = false, DateAdded = DateTime.Now, Requirements = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.", Description = "Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam. Labore et dolore magna aliqua. Ut enim ad minim veniam.", CompanyDescription = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt." },
                new Offer() { OfferId = 4, CategoryId = 2, Status = OfferStatus.Aktywne, Title = "Mid TypeScript Developer (zdalnie)", Type = "Pełny etat", Salary = "8 500 zł./mies.", CompanyName = "Fast Blue Engine", CompanyWebsite = "fast-b-engine.com", CompanyPhotoSource = "company4.png", Featured = true, DateAdded = DateTime.Now, Requirements = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.", Description = "Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam. Labore et dolore magna aliqua. Ut enim ad minim veniam.", CompanyDescription = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt." },
                new Offer() { OfferId = 5, CategoryId = 2, Status = OfferStatus.Aktywne, Title = "Senior TypeScript Developer", Type = "1/4 etatu", Salary = "9 500 zł./mies.", CompanyName = "Top Inline", CompanyWebsite = "topinline.com", CompanyPhotoSource = "company5.png", Featured = false, DateAdded = DateTime.Now, Requirements = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.", Description = "Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam. Labore et dolore magna aliqua. Ut enim ad minim veniam.", CompanyDescription = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt." },
                new Offer() { OfferId = 6, CategoryId = 2, Status = OfferStatus.Aktywne, Title = "Młodszy programista TypeScript", Type = "Pełny etat", Salary = "8 500 zł./mies.", CompanyName = "Yellow Code", CompanyWebsite = "yellowc.com", CompanyPhotoSource = "company6.png", Featured = false, DateAdded = DateTime.Now, Requirements = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.", Description = "Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam. Labore et dolore magna aliqua. Ut enim ad minim veniam.", CompanyDescription = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt." },
                new Offer() { OfferId = 7, CategoryId = 3, Status = OfferStatus.Aktywne, Title = "Programista Java/Groovy/Kotlin/Scala", Type = "Pełny etat", Salary = "2 500 zł./mies.", CompanyName = "Fast Blue Engine", CompanyWebsite = "fast-b-engine.com", CompanyPhotoSource = "company7.png", Featured = true, DateAdded = DateTime.Now, Requirements = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.", Description = "Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam. Labore et dolore magna aliqua. Ut enim ad minim veniam.", CompanyDescription = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt." },
                new Offer() { OfferId = 8, CategoryId = 3, Status = OfferStatus.Aktywne, Title = "Programista JAVA (Systemy ERP)", Type = "1/2 etatu", Salary = "5 500 zł./mies.", CompanyName = "Tea Mont", CompanyWebsite = "tea-mont.com", CompanyPhotoSource = "company8.png", Featured = false, DateAdded = DateTime.Now, Requirements = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.", Description = "Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam. Labore et dolore magna aliqua. Ut enim ad minim veniam.", CompanyDescription = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt." },
                new Offer() { OfferId = 9, CategoryId = 3, Status = OfferStatus.Aktywne, Title = "Senior Java Backend Engineer", Type = "Pełny etat", Salary = "5 500 zł./mies.", CompanyName = "Top Inline", CompanyWebsite = "topinline.com", CompanyPhotoSource = "company9.png", Featured = false, DateAdded = DateTime.Now, Requirements = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.", Description = "Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam. Labore et dolore magna aliqua. Ut enim ad minim veniam.", CompanyDescription = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt." },
                new Offer() { OfferId = 10, CategoryId = 4, Status = OfferStatus.Aktywne, Title = "Starszy programista React.js", Type = "1/4 etatu", Salary = "8 500 zł./mies.", CompanyName = "Fast Blue Engine", CompanyWebsite = "fast-b-engine.com", CompanyPhotoSource = "company10.png", Featured = true, DateAdded = DateTime.Now, Requirements = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.", Description = "Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam. Labore et dolore magna aliqua. Ut enim ad minim veniam.", CompanyDescription = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt." },
                new Offer() { OfferId = 11, CategoryId = 4, Status = OfferStatus.Aktywne, Title = "Junior Node.js Developer", Type = "Pełny etat", Salary = "5 500 zł./mies.", CompanyName = "Visual Game", CompanyWebsite = "visualgame.com", CompanyPhotoSource = "company11.png", Featured = false, DateAdded = DateTime.Now, Requirements = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.", Description = "Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam. Labore et dolore magna aliqua. Ut enim ad minim veniam.", CompanyDescription = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt." },
                new Offer() { OfferId = 12, CategoryId = 4, Status = OfferStatus.Aktywne, Title = "Mid JavaScript Developer (zdalnie)", Type = "3/5 etatu", Salary = "8 500 zł./mies.", CompanyName = "Fast Blue Engine", CompanyWebsite = "fast-b-engine.com", CompanyPhotoSource = "company12.png", Featured = false, DateAdded = DateTime.Now, Requirements = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.", Description = "Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam. Labore et dolore magna aliqua. Ut enim ad minim veniam.", CompanyDescription = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt." },
                new Offer() { OfferId = 13, CategoryId = 5, Status = OfferStatus.Aktywne, Title = "Full-Stack Developer PHP", Type = "Pełny etat", Salary = "8 500 zł./mies.", CompanyName = "FGT Tech", CompanyWebsite = "fgttech.com", CompanyPhotoSource = "company13.png", Featured = true, DateAdded = DateTime.Now, Requirements = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.", Description = "Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam. Labore et dolore magna aliqua. Ut enim ad minim veniam.", CompanyDescription = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt." },
                new Offer() { OfferId = 14, CategoryId = 5, Status = OfferStatus.Aktywne, Title = "Senior PHP Developer", Type = "Pełny etat", Salary = "4 500 zł./mies.", CompanyName = "Fast Blue Engine", CompanyWebsite = "fast-b-engine.com", CompanyPhotoSource = "company14.png", Featured = false, DateAdded = DateTime.Now, Requirements = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.", Description = "Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam. Labore et dolore magna aliqua. Ut enim ad minim veniam.", CompanyDescription = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt." },
                new Offer() { OfferId = 15, CategoryId = 5, Status = OfferStatus.Aktywne, Title = "Web/PHP Developer", Type = "1/2 etatu", Salary = "8 500 zł./mies.", CompanyName = "Visual Game", CompanyWebsite = "visualgame.com", CompanyPhotoSource = "company15.png", Featured = false, DateAdded = DateTime.Now, Requirements = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.", Description = "Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam. Labore et dolore magna aliqua. Ut enim ad minim veniam.", CompanyDescription = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt." },
                new Offer() { OfferId = 16, CategoryId = 6, Status = OfferStatus.Aktywne, Title = "Devops Python/GO Engineer", Type = "Pełny etat", Salary = "6 500 zł./mies.", CompanyName = "Top Inline", CompanyWebsite = "top-inline.com", CompanyPhotoSource = "company16.png", Featured = true, DateAdded = DateTime.Now, Requirements = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.", Description = "Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam. Labore et dolore magna aliqua. Ut enim ad minim veniam.", CompanyDescription = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt." },
                new Offer() { OfferId = 17, CategoryId = 6, Status = OfferStatus.Aktywne, Title = "Młodszy programista Django", Type = "Pełny etat", Salary = "8 500 zł./mies.", CompanyName = "Yellow Code", CompanyWebsite = "yellowcode.com", CompanyPhotoSource = "company17.png", Featured = false, DateAdded = DateTime.Now, Requirements = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.", Description = "Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam. Labore et dolore magna aliqua. Ut enim ad minim veniam.", CompanyDescription = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt." },
                new Offer() { OfferId = 18, CategoryId = 6, Status = OfferStatus.Aktywne, Title = "C++/Python Developer", Type = "3/5 etatu", Salary = "8 500 zł./mies.", CompanyName = "Visual Game", CompanyWebsite = "visualgame.com", CompanyPhotoSource = "company18.png", Featured = false, DateAdded = DateTime.Now, Requirements = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.", Description = "Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam. Labore et dolore magna aliqua. Ut enim ad minim veniam.", CompanyDescription = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt." },
                new Offer() { OfferId = 19, CategoryId = 7, Status = OfferStatus.Aktywne, Title = "Starszy programista C#", Type = "Pełny etat", Salary = "8 500 zł./mies.", CompanyName = "FGT Tech", CompanyWebsite = "fgttech.com", CompanyPhotoSource = "company1.png", Featured = false, DateAdded = DateTime.Now, Requirements = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.", Description = "Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam. Labore et dolore magna aliqua. Ut enim ad minim veniam.", CompanyDescription = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt." },
                new Offer() { OfferId = 20, CategoryId = 7, Status = OfferStatus.Aktywne, Title = "Regular ASP.NET MVC Developer", Type = "1/2 etatu", Salary = "10 500 zł./mies.", CompanyName = "Tea Mont", CompanyWebsite = "tea-mont.com", CompanyPhotoSource = "company2.png", Featured = false, DateAdded = DateTime.Now, Requirements = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.", Description = "Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam. Labore et dolore magna aliqua. Ut enim ad minim veniam.", CompanyDescription = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt." },
                new Offer() { OfferId = 21, CategoryId = 7, Status = OfferStatus.Aktywne, Title = "WinForms/WPF Developer (remote)", Type = "Pełny etat", Salary = "8 500 zł./mies.", CompanyName = "Top Inline", CompanyWebsite = "topinline.com", CompanyPhotoSource = "company3.png", Featured = false, DateAdded = DateTime.Now, Requirements = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.", Description = "Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam. Labore et dolore magna aliqua. Ut enim ad minim veniam.", CompanyDescription = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt." }
             };
            offers.ForEach(x => context.Offers.AddOrUpdate(x));
            context.SaveChanges();
        }

        public static void SeedUsers(FlyRemotelyContext db)
        {
            var userManager = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(db));
            var roleManager = new RoleManager<IdentityRole>(new RoleStore<IdentityRole>(db));

            const string name = "admin@flyremotely.pl";
            const string password = "Admin1!";
            const string roleName = "Admin";

            var user = userManager.FindByName(name);
            if (user == null)
            {
                user = new ApplicationUser { UserName = name, Email = name };
                var result = userManager.Create(user, password);
            }

            // create the Admin role if it does not exist
            var role = roleManager.FindByName(roleName);
            if (role == null)
            {
                role = new IdentityRole(roleName);
                var roleresult = roleManager.Create(role);
            }

            // adding a user to the Admin role if it is not assigned
            var rolesForUser = userManager.GetRoles(user.Id);
            if (!rolesForUser.Contains(role.Name))
            {
                var result = userManager.AddToRole(user.Id, role.Name);
            }
        }
    }
}