// <auto-generated />
namespace FlyRemotely.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class addApplicationEmailtomodel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addApplicationEmailtomodel));
        
        string IMigrationMetadata.Id
        {
            get { return "202009040817062_add ApplicationEmail to model"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
